const mongoose = require('mongoose');

const ChatMessageSchema = new mongoose.Schema({
  session: {
    type: mongoose.Schema.ObjectId,
    ref: 'ChatSession',
    required: true,
    index: true, // Index for faster querying of messages by session
  },
  sender: {
    type: String,
    required: true,
    enum: ['user', 'ai'], // Define who sent the message
  },
  content: {
    type: String,
    required: false, // Allow messages with only files
    trim: true,
  },
  timestamp: {
    type: Date,
    default: Date.now,
  },
  fileInfo: { // Add field to store uploaded file details
      type: {
          filename: String,     // Name generated by multer (unique)
          originalname: String, // Original name from user's computer
          mimetype: String,
          size: Number,
          path: String
      },
      required: false
  },
  modelUsed: { // Store the model that generated the AI response
      type: String,
      required: false // Only applicable for AI messages
  },
  reasoningContent: { // Add field for reasoning steps/content
      type: String,
      required: false
  },
  // Optional: Add fields for feedback, ratings, etc.
  // rating: {
  //   type: Number, // e.g., 1-5 stars
  // },
  // feedback: {
  //   type: String,
  // }
});

module.exports = mongoose.model('ChatMessage', ChatMessageSchema);
